### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by jirutka** [WebReflection/ascjs#11]
```
ascjs --ignore=main.mjs src/ lib/

 | /packages/asciidoctor/project/node_modules/ascjs/bin.js:15
 |           .map(file => path.resolve(__dirname, file))
 |                             ^
 | 
 | ReferenceError: path is not defined
 |     at ignore.push.apply.arg.slice.replace.split.map.file packages/asciidoctor/(project/node_modules/ascjs/bin.js:15:29)
 |     at Array.map (<anonymous>)
 |     at options.forEach.arg packages/asciidoctor/(project/node_modules/ascjs/bin.js:15:12)
 |     at Array.forEach (<anonymous>)
 |     at Object.<anonymous> packages/asciidoctor/(project/node_modules/ascjs/bin.js:10:9)
 |     at Module._compile (module.js:653:30)
 |     at Object.Module._extensions..js (module.js:664:10)
 |     at Module.load (module.js:566:32)
 |     at tryModuleLoad (module.js:506:12)
 |     at Function.Module._load (module.js:498:3)
```

**Comment by WebReflection** [comment]
Truth to be told, I don't care much about `.mjs` so any PR would be more than welcome here.

**Comment by jirutka** [comment]
This has nothing to do with `.mjs`, but the `--ignore` option – `path` is used before it’s required.

**Comment by WebReflection** [comment]
@jirutka apologies, you're right. Fixed as patch, thanks for filing a bug 👋
